[package]
name = "magma_ecs"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"
description = "Entity-Component-System for the Magma3D game engine"
repository = "https://github.com/DynamicGoose/mecs"

[dependencies]
thiserror = "1.0.50"
